# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Title.setGeometry(QtCore.QRect(230, 20, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.label_PlainText = QtWidgets.QLabel(self.centralwidget)
        self.label_PlainText.setGeometry(QtCore.QRect(10, 100, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_PlainText.setFont(font)
        self.label_PlainText.setObjectName("label_PlainText")
        self.label_Key = QtWidgets.QLabel(self.centralwidget)
        self.label_Key.setGeometry(QtCore.QRect(10, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_Key.setFont(font)
        self.label_Key.setObjectName("label_Key")
        self.label_CipherText = QtWidgets.QLabel(self.centralwidget)
        self.label_CipherText.setGeometry(QtCore.QRect(10, 380, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_CipherText.setFont(font)
        self.label_CipherText.setObjectName("label_CipherText")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(170, 100, 671, 121))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(170, 380, 671, 121))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.txt_Key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(170, 270, 661, 31))
        self.txt_Key.setObjectName("txt_Key")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(170, 520, 101, 31))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(710, 520, 101, 31))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Playfair Cipher"))
        self.label_Title.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.label_PlainText.setText(_translate("MainWindow", "Plain Text :"))
        self.label_Key.setText(_translate("MainWindow", "Key :"))
        self.label_CipherText.setText(_translate("MainWindow", "CipherText :"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
